name: Build App

on:
  pull_request:
  push:
    branches:
      - main
      # - release

env:
  # Our build metadata
  BUILD_USER: android-builder
  BUILD_HOST: github.syncthing.net

jobs:
  build:
    name: Debug Build
    runs-on: ubuntu-latest
    container: ghcr.io/FrederickGeek8/syncthing-android-builder
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            /opt/gocache
          key: ${{ runner.os }}-go1.22.7-${{ hashFiles('syncthing/src/github.com/syncthing/syncthing/go.sum') }}

      - name: build
        run: |
          git config --system --add safe.directory '*'
          java -version
          ./gradlew --no-daemon buildNative lint assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: syncthing-android-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - uses: actions/upload-artifact@v4
        with:
          name: reports-and-libs
          path: |
            app/build/reports/**
            app/src/main/jniLibs/**
